### ISSUE TITLE
프로젝트 기술 스택 결정하기

### ISSUE THREAD

**Issue by soheekimdev** [orlein/advanced-class-project-team-b#2]
# 프로젝트 기술 스택 결정하기
의논하면서 최종적으로 수정/추가되는 내용은 코드블럭으로 표시하겠습니다.

### 프로젝트 기술 스택
- Framework/Library: `React`
- Dev Runtime: `Node.js`
- Bundler: `Vite`
- Language: `TypeScript`
- Routing: `React Router`
- State Management: `Redux`
- Styling: `tailwindcss`, `shadcn`
- HTTP Client: `Axios`
- Unit Test: (투 비 컨티뉴..)

**Comment by soheekimdev** [comment]
추가한 내용은 코드블럭으로 표시하였습니다.

**Comment by Ju-MINJAE** [comment]
Routing은 React Router 어떠신가요 ?

**Comment by Kwonyeojiny** [comment]
> Routing은 React Router 어떠신가요 ?

좋습니다 배운거 써보죠

**Comment by soheekimdev** [comment]
State Management는 강사님이 추천하신(그리고 우리가 앞으로 배울) 리덕스로 갈까요?
(아직 아무것도 쓸 줄 모르지만..)

**Comment by Ju-MINJAE** [comment]
HTTP Client와 Unit Test는  나중에 채우시죠 !

**Comment by Kwonyeojiny** [comment]
> State Management는 강사님이 추천하신(그리고 우리가 앞으로 배울) 리덕스로 갈까요? (아직 아무것도 쓸 줄 모르지만..)

좋습니다 Recoil만 지나가듯 써봐서 redux써보면서 배워보죠

**Comment by Ju-MINJAE** [comment]
> State Management는 강사님이 추천하신(그리고 우리가 앞으로 배울) 리덕스로 갈까요?
(아직 아무것도 쓸 줄 모르지만..)

좋아요 @soheekimdev

**Comment by Kwonyeojiny** [comment]
> HTTP Client와 Unit Test는 나중에 채우시죠 !



> HTTP Client와 Unit Test는 나중에 채우시죠 !

일단 HTTP Client관련해서 저는 axios가 제일 익숙하게 보이긴합니다

**Comment by soheekimdev** [comment]
> 일단 HTTP Client관련해서 저는 axios가 제일 익숙하게 보이긴합니다
그럼 익숙하신 분이 계시니까 밑고 axios 어떠십니까 @Ju-MINJAE

**Comment by soheekimdev** [comment]
### 프로젝트 기술 스택
- Framework/Library: React
- Dev Runtime: Node.js
- Bundler: Vite
- Language: TypeScript
- Routing: React Router
- State Management: Redux
- Styling: tailwindcss, shadcn
- HTTP Client: Axios
- Unit Test: (추후 작성)

위 내용으로 결정되었습니다.

[dee307f](https://github.com/orlein/advanced-class-project-team-b/pull/5/commits/dee307f23059e767f1d06eb1aa3e6c9a9453990e)
