### ISSUE TITLE
2주차 (10/30 - 11/3): [알림 설정] 알림 설정 UI/UX 디자인

### ISSUE THREAD

**Issue by orlein** [orlein/advanced-class-project-team-b#26]
## 알림 설정 UI/UX 디자인
 - [x] 사용자 인터페이스 설계 
 - [x] 보여줄 정보와 알림 설정 방법 확정

**Comment by soheekimdev** [comment]
[Figjam](https://www.figma.com/board/SbViLqC9SOzrDPunS5OPoX/%EC%BB%A4%EB%AE%A4%EB%8B%88T?node-id=101-345&t=qBekoMr3Ahd2H6AI-1)에서 UI 설계 및 기획 결정 완료
