### ISSUE TITLE
프로젝트 소개 내용 작성하기

### ISSUE THREAD

**Issue by Kwonyeojiny** [orlein/advanced-class-project-team-b#3]
### 프로젝트 소개
- 프로젝트 명: 커뮤니'**T**'
- 팀원: [김소희](https://github.com/soheekimdev), [권여진](https://github.com/Kwonyeojiny), [주민재](https://github.com/Ju-MINJAE)
- 프로젝트 개요:
- 기술 스택:

**Comment by soheekimdev** [comment]
제가 #2 제목과 내용을 전체 README.md 내용으로 변경했는데, 다시 서브 타이틀 별로 쪼갤까요?

**Comment by Kwonyeojiny** [comment]
지금 이슈 삭제하려고 찾아보고 있습니다

**Comment by Ju-MINJAE** [comment]
이슈 삭제는 없습니다 하하

**Comment by Kwonyeojiny** [comment]
보기 좋게 쪼개서.. 합시다.

**Comment by soheekimdev** [comment]
넵 그럼 이슈 2번은 다시 이전 내용으로 돌리겠습니다.

**Comment by Kwonyeojiny** [comment]
저희는 팀명 좋은거 없을까요 
지피티한테 물어보고 올게요


- 세모난 개발자들
세 명의 개발자가 모여서 각자 개성이 뚜렷하다는 뜻에서 "세모난"이라고 표현했어요.
- 버그 버스터즈
코딩 중에 나오는 버그들을 "버스터즈"라는 표현으로 유쾌하게 잡아낸다는 의미에요. 영화 "고스트버스터즈"에서 따온 패러디 느낌도 있어요.
- 코드 맛집
요즘 유행하는 "맛집"이라는 단어를 활용해서, 좋은 코드를 맛보여주는 팀이라는 뜻이에요.
- 개발삼국지
세 명이 주축인 팀이라는 것을 중국 역사 "삼국지"에 빗대어 표현했어요. 각자 다른 역할을 맡으면서 힘을 합치는 느낌이에요.
- 코딩 삼총사
"삼총사"라는 익숙한 말로 세 명의 협력을 재밌게 표현했어요. 모험을 떠나는 느낌도 있죠!
- 버그벤저스
"어벤저스"처럼 문제를 해결하는 히어로들, 즉 버그를 퇴치하는 팀을 의미해요. 유쾌한 히어로 느낌!
- 소프트웨어 탐정단
코드에서 문제를 찾고 해결하는 것을 탐정처럼 표현했어요. 무언가를 발견하고 풀어내는 재미있는 이미지에요.
- 메가바이트 삼인조
세 명이 합쳐서 큰 데이터를 다룬다는 의미에서 "메가바이트"로 표현해봤어요. 팀이 큰 힘을 발휘한다는 느낌이죠!
- 키보드 위의 삼남매
세 명이 가족처럼 팀워크가 좋다는 것을 유쾌하게 표현했어요. "삼남매"는 친근하고 재미있게 다가오죠.

아...

**Comment by soheekimdev** [comment]
ㅋㅋㅋㅋㅋㅋ 저도 클로드한테 물어봤어요

멋진 팀명을 몇 가지 제안해 드리겠습니다. 이 팀명들은 프론트엔드 개발의 특성과 3명의 팀원을 고려하여 만들어졌습니다:

"Trio.js"
- JavaScript를 연상시키면서 3명의 팀을 나타냅니다.

"ReactiveThree"
- React와 반응성을 연상시키며, 3명의 팀원을 나타냅니다.

"FrontierForge"
- 프론트엔드의 'Front'와 개척자를 의미하는 'Frontier', 그리고 만들어낸다는 의미의 'Forge'를 결합했습니다.

"PixelPioneers"
- 웹 디자인의 기본 단위인 픽셀과 개척자를 의미하는 단어를 결합했습니다.

"DOMineers"
- DOM(Document Object Model)과 엔지니어를 결합한 언어유희입니다.

"StyleSquad"
- CSS 스타일링을 연상시키는 'Style'과 팀을 의미하는 'Squad'를 결합했습니다.

"RendeRockets"
- 렌더링(Render)과 로켓(Rockets)을 결합하여 빠른 개발과 혁신을 암시합니다.

"ViewPort Virtuosos"
- 웹 디자인 용어인 'ViewPort'와 숙련된 전문가를 의미하는 'Virtuosos'를 결합했습니다.

"Trinity.dev"
- 3명의 팀원을 나타내는 'Trinity'와 개발자 도메인 '.dev'를 결합했습니다.

"Flex Faction"
- CSS Flexbox를 연상시키는 'Flex'와 팀을 의미하는 'Faction'을 결합했습니다.

=====

물론이죠! 한글로 된 창의적이고 재미있는 팀명을 제안해 드리겠습니다. 이 팀명들은 프론트엔드 개발의 특성과 3명의 팀원을 고려하여 만들어졌습니다:

"삼색화면"
- 3명의 팀원과 화면 개발을 의미합니다.

"프론트쓰리"
- 프론트엔드와 3명의 팀을 나타냅니다.

"화면조각사"
- UI를 만드는 작업을 예술적으로 표현했습니다.

"삼단폭포"
- 3명의 팀원과 폭포수 개발 방법론을 연상시킵니다.

"픽셀농부"
- 픽셀을 가꾸는 농부처럼 UI를 개발한다는 의미입니다.

"태그틀기술단"
- HTML 태그와 '잘 틀어낸다'는 의미를 결합했습니다.

"렌더링삼총사"
- 렌더링과 3명의 팀원을 재미있게 표현했습니다.

"화면짜기장인"
- UI 개발을 장인 정신과 연결지었습니다.

"눈밝은삼형제"
- UI에 대한 안목과 3명의 팀원을 표현했습니다.

"코드요리사"
- 코드로 멋진 UI를 만드는 것을 요리에 비유했습니다.

"삼색팔레트"
- 3명의 팀원과 다양한 디자인 요소를 표현합니다.

"프론트엔드문파"
- 프론트엔드 개발을 하나의 무술 문파처럼 표현했습니다.

**Comment by Kwonyeojiny** [comment]
좋은 생각이 떠올랐습니다 
소희님도 mbti T 맞으신가요
그렇다면 저희 다 T라 

**커뮤니'T'**
영어로는 communi'T'

저희 프로젝트 주제에 너무나도 딱 맞지 않나요

**Comment by Ju-MINJAE** [comment]
>좋은 생각이 떠올랐습니다
소희님도 mbti T 맞으신가요
그렇다면 저희 다 T라
>
>커뮤니'T'
영어로는 communi'T'
>
>저희 프로젝트 주제에 너무나도 딱 맞지 않나요

커뮤니T 좋습니다. T 99 입니다

**Comment by soheekimdev** [comment]
> 좋은 생각이 떠올랐습니다 소희님도 mbti T 맞으신가요 그렇다면 저희 다 T라
> 
> 커뮤니'**T**' 영어로는 communi'**T**'
> 
> 저희 프로젝트 주제에 너무나도 딱 맞지 않나요
> 
> * 혹은 E_T_니까
>   **E.T.**
>   도 있습니다

헉스 좋습니다 커뮤니T.
ㅋㅋㅋㅋㅋㅋ 저 E T 입니다.
