### ISSUE TITLE
개발 방법 세부 내용 결정하기

### ISSUE THREAD

**Issue by Kwonyeojiny** [orlein/advanced-class-project-team-b#4]
### 개발 방법

- 사용 가능한 Editor / IDE : VSCode, ...
- 개발 환경 설정 방법:
- 로컬 개발 방법:
- PR 방법:
- Issue 관리 방법:
- 커밋 메시지 규칙:

커밋 유형 | 의미
-- | --
Feat | 새로운 기능 추가
Fix | 버그 수정
Docs | 문서 수정
Style | 코드 formatting, 세미콜론 누락, 코드 자체의 변경이 없는 경우
Refactor | 코드 리팩토링
Test | 테스트 코드, 리팩토링 테스트 코드 추가
Chore | 패키지 매니저 수정, 그 외 기타 수정 ex) .gitignore
Design | CSS 등 사용자 UI 디자인 변경
Comment | 필요한 주석 추가 및 변경
Rename | 파일 또는 폴더 명을 수정하거나 옮기는 작업만인 경우
Remove  or Delete | 파일을 삭제하는 작업만 수행한 경우
!BREAKING CHANGE | 커다란 API 변경의 경우
!HOTFIX | 급하게 치명적인 버그를 고쳐야 하는 경우

**Comment by Ju-MINJAE** [comment]
커밋 유형 | 의미
-- | --
Feat | 새로운 기능 추가
Fix | 버그 수정
Docs | 문서 수정
Style | 코드 formatting, 세미콜론 누락, 코드 자체의 변경이 없는 경우
Refactor | 코드 리팩토링
Test | 테스트 코드, 리팩토링 테스트 코드 추가
Chore | 패키지 매니저 수정, 그 외 기타 수정 ex) .gitignore
Design | CSS 등 사용자 UI 디자인 변경
Comment | 필요한 주석 추가 및 변경
Rename | 파일 또는 폴더 명을 수정하거나 옮기는 작업만인 경우
Remove  or Delete | 파일을 삭제하는 작업만 수행한 경우
!BREAKING CHANGE | 커다란 API 변경의 경우
!HOTFIX | 급하게 치명적인 버그를 고쳐야 하는 경우
