### ISSUE TITLE
3주~5주차 (11/6 - 11/26): [글 상세/삭제] 글 상세 페이지 UI/UX 디자인

### ISSUE THREAD

**Issue by orlein** [orlein/advanced-class-project-team-b#40]
## 글 상세 페이지 UI/UX 디자인
 - [x] 사용자 경험을 고려한 레이아웃 설계

**Comment by Ju-MINJAE** [comment]
댓글 작업을 위해 상제 페이지만 만들었습니다.
현재 작성자 author가 공백으로 표시되며, 추후 UI UX 디자인과 같이 수정할 예정입니다.
