### ISSUE TITLE
배포 관련 사항 결정하기

### ISSUE THREAD

**Issue by Kwonyeojiny** [orlein/advanced-class-project-team-b#7]
- 배포 환경 : Vercel
- 배포 방법 : Vercel CI/CD를 통한 자동 배포
- CI/CD : GitHub Actions를 통해 Vercel로 자동 배포 설정
- 배포 주소:
  - [권여진](https://advanced-class-project-yeojin.vercel.app/)
  - [주민재](https://advanced-class-project.vercel.app/)
  - [김소희](https://advanced-class-project-team-b-seven.vercel.app/)

**Comment by Ju-MINJAE** [comment]
https://advanced-class-project.vercel.app/

제 배포 주소입니다.

**Comment by Ju-MINJAE** [comment]
배포 방법: Vercel CI/CD를 통한 자동 배포
CI/CD: GitHub Actions를 통해 Vercel로 자동 배포 설정

**Comment by orlein** [comment]
https://github.com/orlein/advanced-class-project-team-a/issues/3#issuecomment-2416636843

**Comment by soheekimdev** [comment]
@Kwonyeojiny 여진님 이거 PR 올리신 것 맞나요~?

**Comment by Kwonyeojiny** [comment]
> @Kwonyeojiny 여진님 이거 PR 올리신 것 맞나요~? PR 올려서 적용하고 클로즈해야 할 것 같아요

엇 아니요 해보겠습니다
